export {NewFunnel} from './NewFunnel'
export {GetFunnel} from './GetFunnel'
export {NewPage} from './NewPage'
export {GetPage} from './GetPage'
export {InsertNewOptSubmit} from './AddOptSubmit'
export {GetMyFunnels} from './GetMyFunnels'
export {EditPage} from './SavePage'
export {PublishPage} from './PublishPage'
export {ToggleActivateFunnel} from './ToggleActivateFunnel'
export {AddNewMenu} from './AddNewMenu'
export {RemoveMenu} from './RemoveMenu'
export {EditMenu} from './EditMenu'
export {DeleteFunnel} from './DeleteFunnel'
export {DeletePage} from './DeletePage'
export {default as GetOptSumbits} from './GetOptSumbits'
export {default as EditFunnel} from './EditFunnel'
export {default as CreateFunnelFromTemplate} from './CreateFunnelFromTemplate'
export {default as GetAllTemplates} from './getAllTemplates'
export {default as MakeFunnelAsTemplate} from './makeFunnelAsTemplate'
export {UploadFile} from './UploadFile'
export {default as DuplicateFunnel} from './DuplicateFunnel'
export {default as DuplicatePage} from './DuplicatePage'
